#!/bin/sh
set -e

if [ $(basename $(pwd)) != "git-deploy" ]; then
   echo "Please only execute this from the git-deploy directory"
   exit 1
fi

if [ $HOSTNAME != "bkbuild-02.prod.lhr1.booking.com" ] ; then
    echo "This script only works on bkbuild-02"
    exit 1
fi

git status > /dev/null 2>&1 ||
if [ $? -ge 128 ]; then
   echo "Not a git tree."
   exit 1
fi

echo Updating git tree
git pull --rebase

echo "Preparing specfile"
ver=$(awk '/Version:/ { print $2 }' misc/git-deploy.spec)
rel=$(awk '/Release:/ { print $2 }' misc/git-deploy.spec)
cp misc/git-deploy.spec /usr/src/packages/git-deploy

echo Creating .tar.gz
cd ..
tar cfz /usr/src/packages/upstream/git-deploy-$ver-$rel.tar.gz git-deploy
ln -sf ../upstream/git-deploy-$ver-$rel.tar.gz /usr/src/packages/git-deploy/git-deploy-$ver-$rel.tar.gz

echo "Building RPMS with mock"
cd /usr/src/packages
bin/build_package git-deploy
